### ISSUE TITLE
List Spaces Error Code: -11 and Get tags Error: -23

### ISSUE THREAD

**Issue by oldLady344** [vesoft-inc/nebula-java#243]
Exchange 1.1.0 cannot get access to the Meta Service when Nebula Graph is deployed with Docker Compose. 

Here is some information about the images: 

- Here is the image information:
```
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
vesoft/nebula-graphd            nightly             a489b524505e        3 days ago          283MB
vesoft/nebula-metad             nightly             a28667111fdf        3 days ago          288MB
vesoft/nebula-storaged          nightly             664d16ee16de        3 days ago          289MB
```

- When I ran `$SPARK_HOME/bin/spark-submit` to import data, this error occurred: 

```
21/01/04 16:55:52 INFO scheduler.DAGScheduler: Job 1 finished: csv at FileBaseReader.scala:86, took 0.060284 s
21/01/04 16:55:52 ERROR meta.MetaClientImpl: List Spaces Error Code: -11
21/01/04 16:55:52 ERROR meta.MetaClientImpl: Get tags Error: -23
Exception in thread "main" java.util.NoSuchElementException: key not found: courseId
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at com.vesoft.nebula.tools.importer.utils.NebulaUtils$$anonfun$getDataSourceFieldType$1.apply(NebulaUtils.scala:65)
	at com.vesoft.nebula.tools.importer.utils.NebulaUtils$$anonfun$getDataSourceFieldType$1.apply(NebulaUtils.scala:64)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at com.vesoft.nebula.tools.importer.utils.NebulaUtils$.getDataSourceFieldType(NebulaUtils.scala:64)
	at com.vesoft.nebula.tools.importer.processor.VerticesProcessor.process(VerticesProcessor.scala:137)
	at com.vesoft.nebula.tools.importer.Exchange$$anonfun$main$2.apply(Exchange.scala:174)
	at com.vesoft.nebula.tools.importer.Exchange$$anonfun$main$2.apply(Exchange.scala:152)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at com.vesoft.nebula.tools.importer.Exchange$.main(Exchange.scala:152)
	at com.vesoft.nebula.tools.importer.Exchange.main(Exchange.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by Nicole00** [comment]
The latest docker image for version nightly does not allow read meta information from followers.
This problem is caused because client mismatches the server. Client need to be updated.

**Comment by Nicole00** [comment]
https://github.com/vesoft-inc/nebula-java/pull/262 solved this issue.
