### ISSUE TITLE
Storage Client Error

### ISSUE THREAD

**Issue by zcw5116** [vesoft-inc/nebula-java#268]
Nebula Service Version:  2.0-rc1

**### Pom:**

> <dependency>
        <groupId>com.vesoft</groupId>
        <artifactId>client</artifactId>
        <version>2.0.0-rc1</version>
</dependency>

**### My Code:**
`
import com.vesoft.nebula.client.storage.StorageClient;
import com.vesoft.nebula.client.storage.scan.ScanVertexResultIterator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.UnsupportedEncodingException;

public class StorageClientExample {

    private static final Logger LOGGER = LoggerFactory.getLogger(StorageClientExample.class);

    public static void main(String[] args) throws UnsupportedEncodingException {
        StorageClient client = new StorageClient("192.168.11.20", 9779);
        try {
            client.connect();
        } catch (Exception e) {
            LOGGER.error("storage client connect error, ", e);
            System.exit(1);
        }

        ScanVertexResultIterator iterator = client.scanVertex(
                "test",
                "person");
    }

}

`

**### My console output:**

> ERROR [main] - Method name listSpaces not found
ERROR [main] - Method name listSpaces not found
Exception in thread "main" java.lang.IllegalArgumentException: Space:test does not exist.
	at com.vesoft.nebula.client.meta.MetaManager.getPartsAlloc(MetaManager.java:307)
	at com.vesoft.nebula.client.meta.MetaManager.getSpaceParts(MetaManager.java:289)
	at com.vesoft.nebula.client.storage.StorageClient.scanVertex(StorageClient.java:272)
	at com.vesoft.nebula.client.storage.StorageClient.scanVertex(StorageClient.java:154)
	at com.vesoft.nebula.client.storage.StorageClient.scanVertex(StorageClient.java:113)
	at com.vesoft.nebula.client.storage.StorageClient.scanVertex(StorageClient.java:80)
	at com.xiao.demo.StorageClientExample.main(StorageClientExample.java:30)

Process finished with exit code 1

**Comment by laura-ding** [comment]
I'm very sorry that the interface parameters are not specified. What StorageClient passes in is the IP and port of Meta, and StorageClient obtains the corresponding IP and port of storage through metad.

So here need to modify `9779` to `9559`

**Comment by Nicole00** [comment]
https://github.com/vesoft-inc/nebula-java/pull/278 added comment for the parameters.
