### ISSUE TITLE
when graph engine server restart， the connect will be error somtimes

### ISSUE THREAD

**Issue by svenbarnett** [vesoft-inc/nebula-java#457]
error msg：

com.vesoft.nebula.client.graph.exception.IOErrorException: java.net.SocketException: Broken pipe (Write failed)
        at com.vesoft.nebula.client.graph.net.SyncConnection.executeWithParameter(SyncConnection.java:192) ~[client-3.0.0.jar!/:?]
        at com.vesoft.nebula.client.graph.net.Session.executeWithParameter(Session.java:113) ~[client-3.0.0.jar!/:?]
        at com.vesoft.nebula.client.graph.net.Session.execute(Session.java:78) ~[client-3.0.0.jar!/:?]
        at com.vesoft.nebula.client.graph.net.SessionWrapper.execute(SessionWrapper.java:32) ~[client-3.0.0.jar!/:?]

**Comment by Nicole00** [comment]
When graphd server restarted, the old connection will be an invalid connection, and will be keep in NebulaPool. when you getSession and the NebulaPool gives the invalid connection to Session, then you will get the `Broken pipe`.
The NebulaPool should support the `clean invalid connection` feature.
