### ISSUE TITLE
GET SUBGRAPH ERROR

### ISSUE THREAD

**Issue by withgakki** [vesoft-inc/nebula-java#481]
When I execute NGQL like "GET SUBGRAPH WITH PROP 10 STEPS FROM "xxx" OUT BusinessTreeRelationship YIELD VERTICES AS nodes, EDGES AS relationships;" the error occurs:
```
org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Cannot get field 'eVal' because union is currently set to sVal; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Cannot get field 'eVal' because union is currently set to sVal (through reference chain: com.envision.graph.vo.ResponseResult["data"]->java.util.HashMap["Rows"]->java.util.ArrayList[0]->java.util.ArrayList[0]->java.util.ArrayList[0]->com.vesoft.nebula.client.graph.data.Node["id"]->com.vesoft.nebula.client.graph.data.ValueWrapper["value"]->com.vesoft.nebula.Value["eval"])
...
...
...
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Cannot get field 'eVal' because union is currently set to sVal (through reference chain: com.envision.graph.vo.ResponseResult["data"]->java.util.HashMap["Rows"]->java.util.ArrayList[0]->java.util.ArrayList[0]->java.util.ArrayList[0]->com.vesoft.nebula.client.graph.data.Node["id"]->com.vesoft.nebula.client.graph.data.ValueWrapper["value"]->com.vesoft.nebula.Value["eval"])
...
Caused by: java.lang.RuntimeException: Cannot get field 'eVal' because union is currently set to sVal
	at com.vesoft.nebula.Value.__getValue(Value.java:695)
	at com.vesoft.nebula.Value.getEVal(Value.java:789)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by wey-gu** [comment]
@Nicole00 could you help take a look at this, plz?

**Comment by Nicole00** [comment]
```
.RuntimeException: Cannot get field 'eVal' because union is currently set to sVal
```
It looks like because the value you want to get is String type, but use it with asEdge().

**Comment by withgakki** [comment]
@wey-gu version is matched
@Nicole00 
Sorry, my mistake, I re-used ValueWrapper for parsing and json conversion of ResultSet in the business logic, according to ValueWrapper's practice, but only Value.VVAL and Value.EVAL, missing the path type, sorry to bother you all
