### ISSUE TITLE
Verify java client with custom header

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula-java#554]
ERROR
```
caused by: com.vesoft.nebula.client.graph.exception.IOErrorException: HTTP Response code: 404	
at com.vesoft.nebula.client.graph.net.SyncConnection.open(SyncConnection.java:139) ~[client-3.6.1.jar:?]	
at com.vesoft.nebula.client.graph.SessionPool.createSessionObject(SessionPool.java:356) ~[client-3.6.1.jar:?]	
at com.vesoft.nebula.client.graph.SessionPool.init(SessionPool.java:122) ~[client-3.6.1.jar:?]	... 26 more"
}
```
```
Caused by: com.vesoft.nebula.client.graph.exception.IOErrorException: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR	
at com.vesoft.nebula.client.graph.net.SyncConnection.open(SyncConnection.java:139) ~[client-3.6.1.jar:?]	
at com.vesoft.nebula.client.graph.SessionPool.createSessionObject(SessionPool.java:356) ~[client-3.6.1.jar:?]	
at com.vesoft.nebula.client.graph.SessionPool.init(SessionPool.java:122) ~[client-3.6.1.jar:?]	... 26 more"
}
```
Config
```
SessionPoolConfig sessionPoolConfig = new SessionPoolConfig(addresses, graphSpace,
                    "root", "nebula");
            sessionPoolConfig.setUseHttp2(true);
            sessionPoolConfig.setCustomHeaders(customHeaders);
            SessionPool sessionPool = new SessionPool(sessionPoolConfig);
            boolean initResult =  sessionPool.init();
            if (!initResult) {
                LOGGER.error("Failed to init SessionPool.");
            }

Header: ImmutableMap.of("Route-Tag", "xxxx")
```

**Comment by HarrisChu** [comment]
![image](https://github.com/vesoft-inc/nebula-java/assets/1726587/7b56d40a-13ab-4114-bc31-6b783bd2b116)

**Comment by Nicole00** [comment]
![image](https://github.com/vesoft-inc/nebula-java/assets/16240361/b2a52dce-ab62-41ff-9dae-f7cbae0ed40b)

**Comment by wenhaocs** [comment]
Thank you!

**Comment by Nicole00** [comment]
![image](https://github.com/vesoft-inc/nebula-java/assets/16240361/9fedc92f-03cb-4454-a61f-2907b042a873)
