### ISSUE TITLE
ResultSet报NullPointerException

### ISSUE THREAD

**Issue by Qubutol** [vesoft-inc/nebula-java#83]
在nebula中执行：
```
go from hash("player.Tony Parker") over follow yield $$.player.name as name,follow.degree as degree
```
返回Execution succeeded (Time spent: 1.145/1.74 ms)
但是通过java客户端执行报错：
Exception in thread "main" java.lang.NullPointerException
	at com.vesoft.nebula.client.graph.ResultSet.<init>(ResultSet.java:35)
	at com.vesoft.nebula.client.graph.GraphClientImpl.executeQuery(GraphClientImpl.java:128)
代码：
```
String query = "go from hash(\"player.Tony Parker\") over follow yield $$.player.name as name,follow.degree as degree";
        GraphClient client = new GraphClientImpl(addr,port);
        client.setUser("user");
        client.setPassword("password");

        try {
            client.connect();
            client.switchSpace("nba1");
        } catch (TException e) {
            e.printStackTrace();
        }
        ResultSet resultSet = null;
        try {
            resultSet = client.executeQuery(query);
        } catch (ConnectionException e) {
            e.printStackTrace();
        } catch (NGQLException e) {
            e.printStackTrace();
        } catch (TException e) {
            e.printStackTrace();
        }
```

**Comment by jude-zhu** [comment]
which GraphClientImpl version do you use

**Comment by Qubutol** [comment]
> which GraphClientImpl version do you use
1.0.0-rc4.20200323 and rc3 both have this problem

**Comment by Qubutol** [comment]
> which GraphClientImpl version do you use
```
go from hash("player.Tony Parker") over follow yield $$.player.name as name,follow.degree as degree
```
查询执行成功但没有结果返回的时候会报这个错，应该是ResultSet的构造方法取不到columes的原因，在构造方法那里报空指针了

**Comment by VoisLp** [comment]
me too
if graphql no result return, throw nullpoint exception
